### ISSUE TITLE
win10 npm install error

### ISSUE THREAD

**Issue by smile2014** [just-jeb/electron-angular-native#284]
gyp: Call to 'find ./src/native* -name binding.gyp -not -path "./**/node_modules/*" | sed -e s/$/:*/' returned exit status 255 while in binding.gyp. while trying to load binding.gyp

**Comment by just-jeb** [comment]
Are you running it with `git-bash`?

**Comment by smile2014** [comment]
thank you,I am executing the command directly in cmd。。
